module.exports = {
  regions: {
    alphabetical: {
      name: 'Субъекты РФ (по алфавиту)',
      subjects: {
        altai_krai: { name: 'Алтайский край', cities: [
          { key: 'barnaul', name: 'Барнаул', priority: 2 },
          { key: 'biysk', name: 'Бийск', priority: 3 },
          { key: 'rubtsovsk', name: 'Рубцовск', priority: 3 },
          { key: 'novoaltaisk', name: 'Новоалтайск', priority: 3 },
          { key: 'zarinsk', name: 'Заринск', priority: 3 }
        ] },
        amur_oblast: { name: 'Амурская область', cities: [
          { key: 'blagoveshchensk', name: 'Благовещенск', priority: 2 },
          { key: 'belogorsk', name: 'Белогорск', priority: 3 },
          { key: 'svobodny', name: 'Свободный', priority: 3 },
          { key: 'tynda', name: 'Тында', priority: 3 },
          { key: 'raichikhinsk', name: 'Райчихинск', priority: 3 }
        ] },
        adygea: { name: 'Республика Адыгея', cities: [] },
        altai_republic: { name: 'Республика Алтай', cities: [] },
        arkhangelsk_oblast: { name: 'Архангельская область', cities: [
          { key: 'arkhangelsk', name: 'Архангельск', priority: 1 },
          { key: 'severodvinsk', name: 'Северодвинск', priority: 2 },
          { key: 'kotlas', name: 'Котлас', priority: 2 },
          { key: 'novodvinsk', name: 'Новодвинск', priority: 3 },
          { key: 'koryazhma', name: 'Коряжма', priority: 3 },
          { key: 'mirny', name: 'Мирный', priority: 3 },
          { key: 'vyazniki_arkh', name: 'Вязники', priority: 3 },
          { key: 'onega', name: 'Онега', priority: 3 },
          { key: 'mezen', name: 'Мезень', priority: 3 },
          { key: 'shenkursk', name: 'Шенкурск', priority: 3 }
        ] },
        astrakhan_oblast: { name: 'Астраханская область', cities: [
          { key: 'astrakhan', name: 'Астрахань', priority: 1 },
          { key: 'akhtubinsk', name: 'Ахтубинск', priority: 2 },
          { key: 'znamensk', name: 'Знаменск', priority: 2 },
          { key: 'kharabali', name: 'Харабали', priority: 3 },
          { key: 'kamyzyak', name: 'Камызяк', priority: 3 },
          { key: 'narimanov', name: 'Нариманов', priority: 3 },
          { key: 'krasny_yar', name: 'Красный Яр', priority: 3 },
          { key: 'ikryanoye', name: 'Икряное', priority: 3 },
          { key: 'liman', name: 'Лиман', priority: 3 },
          { key: 'volodarsky', name: 'Володарский', priority: 3 }
        ] },
        bashkortostan: { name: 'Республика Башкортостан', cities: [
          { key: 'ufa', name: 'Уфа', priority: 1 },
          { key: 'sterlitamak', name: 'Стерлитамак', priority: 2 },
          { key: 'salavat', name: 'Салават', priority: 2 },
          { key: 'neftekamsk', name: 'Нефтекамск', priority: 2 },
          { key: 'oktyabrsky', name: 'Октябрьский', priority: 2 },
          { key: 'tuymazy', name: 'Туймазы', priority: 3 },
          { key: 'belebey', name: 'Белебей', priority: 3 },
          { key: 'ishimbay', name: 'Ишимбай', priority: 3 },
          { key: 'kumertau', name: 'Кумертау', priority: 3 },
          { key: 'meleuz', name: 'Мелеуз', priority: 3 },
          { key: 'baymak', name: 'Баймак', priority: 3 },
          { key: 'birsk', name: 'Бирск', priority: 3 },
          { key: 'blagoveshchensk_bash', name: 'Благовещенск', priority: 3 },
          { key: 'davlekanovo', name: 'Давлеканово', priority: 3 },
          { key: 'dyurtyuli', name: 'Дюртюли', priority: 3 }
        ] },
        belgorod_oblast: { name: 'Белгородская область', cities: [
          { key: 'belgorod', name: 'Белгород', priority: 1 },
          { key: 'stary_oskol', name: 'Старый Оскол', priority: 2 },
          { key: 'gubkin', name: 'Губкин', priority: 2 },
          { key: 'shebekino', name: 'Шебекино', priority: 3 },
          { key: 'aleksandrovka', name: 'Александровка', priority: 3 },
          { key: 'valuyki', name: 'Валуйки', priority: 3 },
          { key: 'krasnogvardeyskoye', name: 'Красногвардейское', priority: 3 },
          { key: 'novy_oskol', name: 'Новый Оскол', priority: 3 },
          { key: 'biryuch', name: 'Бирюч', priority: 3 },
          { key: 'graivoron', name: 'Грайворон', priority: 3 },
          { key: 'korocha', name: 'Короча', priority: 3 },
          { key: 'rakiytnoye', name: 'Ракитное', priority: 3 },
          { key: 'volokonovka', name: 'Волоконовка', priority: 3 },
          { key: 'chernyanka', name: 'Чернянка', priority: 3 },
          { key: 'yakovlevo', name: 'Яковлево', priority: 3 }
        ] },
        bryansk_oblast: { name: 'Брянская область', cities: [] },
        buryatia: { name: 'Республика Бурятия', cities: [] },
        vladimir_oblast: { name: 'Владимирская область', cities: [
          { key: 'vladimir', name: 'Владимир', priority: 1 },
          { key: 'kovrov', name: 'Ковров', priority: 2 },
          { key: 'murom', name: 'Муром', priority: 2 },
          { key: 'alexandrov', name: 'Александров', priority: 2 },
          { key: 'gus_khrustalny', name: 'Гусь-Хрустальный', priority: 3 },
          { key: 'vyazniki', name: 'Вязники', priority: 3 },
          { key: 'kirzhach', name: 'Киржач', priority: 3 },
          { key: 'pokrov', name: 'Покров', priority: 3 },
          { key: 'petushki', name: 'Петушки', priority: 3 },
          { key: 'raduzhny', name: 'Радужный', priority: 3 },
          { key: 'struino', name: 'Струнино', priority: 3 },
          { key: 'karabanovo', name: 'Карабаново', priority: 3 },
          { key: 'lakinsk', name: 'Лакинск', priority: 3 },
          { key: 'melekhovo', name: 'Мелехово', priority: 3 },
          { key: 'gorokhovets', name: 'Гороховец', priority: 3 }
        ] },
        volgograd_oblast: { name: 'Волгоградская область', cities: [] },
        vologda_oblast: { name: 'Вологодская область', cities: [] },
        voronezh_oblast: { name: 'Воронежская область', cities: [] },
        dagestan: { name: 'Республика Дагестан', cities: [] },
        jewish_ao: { name: 'Еврейская автономная область', cities: [] },
        zabaykalsky_krai: { name: 'Забайкальский край', cities: [] },
        ivanovo_oblast: { name: 'Ивановская область', cities: [] },
        ingushetia: { name: 'Республика Ингушетия', cities: [] },
        irkutsk_oblast: { name: 'Иркутская область', cities: [] },
        kabardino_balkaria: { name: 'Кабардино-Балкарская Республика', cities: [] },
        kaliningrad_oblast: { name: 'Калининградская область', cities: [] },
        kalmykia: { name: 'Республика Калмыкия', cities: [] },
        kaluga_oblast: { name: 'Калужская область', cities: [] },
        kamchatka_krai: { name: 'Камчатский край', cities: [] },
        karachay_cherkessia: { name: 'Карачаево-Черкесская Республика', cities: [] },
        karelia: { name: 'Республика Карелия', cities: [] },
        kemerovo_oblast: { name: 'Кемеровская область — Кузбасс', cities: [] },
        kirov_oblast: { name: 'Кировская область', cities: [] },
        komi: { name: 'Республика Коми', cities: [] },
        kostroma_oblast: { name: 'Костромская область', cities: [] },
        krasnodar_krai: { name: 'Краснодарский край', cities: [] },
        krasnoyarsk_krai: { name: 'Красноярский край', cities: [] },
        crimea: { name: 'Республика Крым', cities: [] },
        kurgan_oblast: { name: 'Курганская область', cities: [] },
        kursk_oblast: { name: 'Курская область', cities: [] },
        leningrad_oblast: { name: 'Ленинградская область', cities: [] },
        lipetsk_oblast: { name: 'Липецкая область', cities: [] },
        magadan_oblast: { name: 'Магаданская область', cities: [] },
        mari_el: { name: 'Республика Марий Эл', cities: [] },
        mordovia: { name: 'Республика Мордовия', cities: [] },
        moscow_city: { name: 'Москва', cities: [] },
        moscow_oblast: { name: 'Московская область', cities: [
          { key: 'podolsk', name: 'Подольск', priority: 2 },
          { key: 'khimki', name: 'Химки', priority: 2 },
          { key: 'korolev', name: 'Королёв', priority: 2 },
          { key: 'mytishchi', name: 'Мытищи', priority: 2 },
          { key: 'lyubertsy', name: 'Люберцы', priority: 2 },
          { key: 'elektrostal', name: 'Электросталь', priority: 3 },
          { key: 'kolomna', name: 'Коломна', priority: 2 },
          { key: 'odintsovo', name: 'Одинцово', priority: 3 },
          { key: 'serpukhov', name: 'Серпухов', priority: 2 },
          { key: 'orekhovo_zuevo', name: 'Орехово-Зуево', priority: 3 },
          { key: 'noginsk', name: 'Ногинск', priority: 3 },
          { key: 'shchelkovo', name: 'Щёлково', priority: 3 },
          { key: 'balashikha', name: 'Балашиха', priority: 2 },
          { key: 'pushkino', name: 'Пушкино', priority: 3 },
          { key: 'zhukovsky', name: 'Жуковский', priority: 3 }
        ] },
        murmansk_oblast: { name: 'Мурманская область', cities: [] },
        nenets_ao: { name: 'Ненецкий автономный округ', cities: [] },
        nizhny_novgorod_oblast: { name: 'Нижегородская область', cities: [] },
        novgorod_oblast: { name: 'Новгородская область', cities: [] },
        novosibirsk_oblast: { name: 'Новосибирская область', cities: [] },
        omsk_oblast: { name: 'Омская область', cities: [] },
        orenburg_oblast: { name: 'Оренбургская область', cities: [] },
        oryol_oblast: { name: 'Орловская область', cities: [] },
        penza_oblast: { name: 'Пензенская область', cities: [] },
        perm_krai: { name: 'Пермский край', cities: [] },
        primorsky_krai: { name: 'Приморский край', cities: [] },
        pskov_oblast: { name: 'Псковская область', cities: [] },
        rostov_oblast: { name: 'Ростовская область', cities: [] },
        ryazan_oblast: { name: 'Рязанская область', cities: [] },
        samara_oblast: { name: 'Самарская область', cities: [] },
        saratov_oblast: { name: 'Саратовская область', cities: [] },
        sakhalin_oblast: { name: 'Сахалинская область', cities: [] },
        sverdlovsk_oblast: { name: 'Свердловская область', cities: [] },
        sevastopol: { name: 'Севастополь', cities: [] },
        north_ossetia: { name: 'Республика Северная Осетия — Алания', cities: [] },
        smolensk_oblast: { name: 'Смоленская область', cities: [] },
        stavropol_krai: { name: 'Ставропольский край', cities: [] },
        tambov_oblast: { name: 'Тамбовская область', cities: [] },
        tatarstan: { name: 'Республика Татарстан', cities: [] },
        tver_oblast: { name: 'Тверская область', cities: [] },
        tomsk_oblast: { name: 'Томская область', cities: [] },
        tula_oblast: { name: 'Тульская область', cities: [] },
        tuva: { name: 'Республика Тыва', cities: [] },
        tyumen_oblast: { name: 'Тюменская область', cities: [] },
        udmurtia: { name: 'Удмуртская Республика', cities: [] },
        ulyanovsk_oblast: { name: 'Ульяновская область', cities: [] },
        khabarovsk_krai: { name: 'Хабаровский край', cities: [] },
        khakassia: { name: 'Республика Хакасия', cities: [] },
        khanty_mansi_ao: { name: 'Ханты-Мансийский автономный округ — Югра', cities: [] },
        chelyabinsk_oblast: { name: 'Челябинская область', cities: [] },
        chechnya: { name: 'Чеченская Республика', cities: [] },
        chuvashia: { name: 'Чувашская Республика — Чувашия', cities: [] },
        chukotka_ao: { name: 'Чукотский автономный округ', cities: [] },
        yakutia: { name: 'Республика Саха (Якутия)', cities: [] },
        yamal_ao: { name: 'Ямало-Ненецкий автономный округ', cities: [] },
        yaroslavl_oblast: { name: 'Ярославская область', cities: [] }
      }
    }
  }
};